stages:
  - build
  - tests
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  LATEST_IMAGE: "$CI_REGISTRY_IMAGE:latest"

build to gitlab:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker pull $LATEST_IMAGE || true
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --cache-from $LATEST_IMAGE --tag $RELEASE_IMAGE --tag $LATEST_IMAGE .
    - docker push $RELEASE_IMAGE
    - docker push $LATEST_IMAGE
  environment: development
  tags:
    - docker
    - cache

test:
  image: docker:latest
  stage: tests
  services:
    - docker:dind
  script:
    - ./test.sh $RELEASE_IMAGE
  environment: development
  tags:
    - docker
    - cache

deploy to dockerhub:
  image: docker:latest
  stage: deploy
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - docker pull $RELEASE_IMAGE
    - docker tag $RELEASE_IMAGE -t "$DOCKERHUB_IMAGE:$CI_COMMIT_TAG"
    - docker tag $RELEASE_IMAGE -t "$DOCKERHUB_IMAGE:latest"
    - docker push "$DOCKERHUB_IMAGE:$CI_COMMIT_TAG"
    - docker push "$DOCKERHUB_IMAGE:latest"
  only:
    - tags
  environment: production
  tags:
    - docker
    - cache
