stages:
  - build
  - tests
  - deploy

variables:
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

build to gitlab:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t $RELEASE_IMAGE .
    - docker tag $RELEASE_IMAGE "$CI_REGISTRY_IMAGE:latest"
    - docker push $RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE:latest"
  environment: development
  tags:
    - docker
    - cache

test:
  image: $RELEASE_IMAGE
  stage: tests
  services:
    - docker:dind
  script:
    - mix test
  environment: other
  tags:
    - docker
    - cache

deploy to dockerhub:
  image: docker:latest
  stage: deploy
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - docker pull $RELEASE_IMAGE
    - docker tag $RELEASE_IMAGE -t "$DOCKERHUB_IMAGE:$CI_COMMIT_TAG"
    - docker tag $RELEASE_IMAGE -t "$DOCKERHUB_IMAGE:latest"
    - docker push "$DOCKERHUB_IMAGE:$CI_COMMIT_TAG"
    - docker push "$DOCKERHUB_IMAGE:latest"
  only:
    - tags
  environment: production
  tags:
    - docker
    - cache
